version: "2.2"
services:

  rest-api:
    entrypoint: "/src/rest-api/entrypoint"
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:80
    volumes:
      - ".:/src"

    env_file:
      - ./rest-api/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    ports:
      - "8081:80"

    volumes:
      - "./frontend:/src"

  geodb:
    image: mongo
    volumes:
      - "./mongodata:/data/db"

