version: "2.2"
services:

  rest-api:
    entrypoint: "/src/rest-api/entrypoint"
    build:
      context: .
      dockerfile: python_env/Dockerfile
    ports:
      - 8080:80
    volumes:
      - ".:/src"

    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    ports:
      - "8081:80"

    volumes:
      - "./frontend:/src"

  geodb:
    image: mongo
    volumes:
      - "./mongodata:/data/db"
    ports:
      - 27017:27017

  cachedb:
    image: redis

  geojson-loader:
    command: ["ls"]
    build:
      context: .
      dockerfile: python_env/Dockerfile
    env_file:
    - .env

    volumes:
      - .:/src


