version: "2.2"
services:

  deploy-api:
    entrypoint: "/src/rest-api/entrypoint"
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:80
    env_file:
      - .env

  geodb:
    image: mongo

